export const HTTP_HEADERS = {
  X_LOADING: 'X-LOADING',
  X_CAPTCHA_HEADER: 'X-KAPTCHA-HEADER',
  X_TRANSACTION_ID: 'X-TRANSACTION-ID',
  AUTHORIZATION: 'Authorization',
  AUTHORIZATION_TYPE: 'Bearer ',
  LOCALE: 'language',
  X_IGNORE_ERROR: 'X-SHOW-ERROR',
};
