export enum SCOPE {
  VIEW = 'view',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum RESOURCE {
  FILE = 'file',
  NOTIFICATION = 'notification',
  ROLE = 'role',
  USER = 'user',
  MEETING = 'meeting',
  ORDER = 'order',
  ROOM = 'room',
  DEPARTMENT = 'department',
  EMPLOYEE = 'employee',
  CLIENT = 'client',
  CONTRACT = 'contract'
}

export const PERMISSION_CONSTANT = {
  FILE: {
    VIEW: `${RESOURCE.FILE}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.FILE}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.FILE}:${SCOPE.UPDATE}`,
  },
  NOTIFICATION: {
    VIEW: `${RESOURCE.NOTIFICATION}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.NOTIFICATION}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.NOTIFICATION}:${SCOPE.UPDATE}`,
    DELETE: `${RESOURCE.NOTIFICATION}:${SCOPE.DELETE}`,
  },
  ROLE: {
    VIEW: `${RESOURCE.ROLE}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.ROLE}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.ROLE}:${SCOPE.UPDATE}`,
  },
  USER: {
    VIEW: `${RESOURCE.USER}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.USER}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.USER}:${SCOPE.UPDATE}`,
  },
  MEETING: {
    VIEW: `${RESOURCE.MEETING}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.MEETING}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.MEETING}:${SCOPE.UPDATE}`,
  },
  ORDER: {
    VIEW: `${RESOURCE.ORDER}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.ORDER}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.ORDER}:${SCOPE.UPDATE}`,
  },
  ROOM: {
    VIEW: `${RESOURCE.ROOM}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.ROOM}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.ROOM}:${SCOPE.UPDATE}`,
  },
  DEPARTMENT: {
    VIEW: `${RESOURCE.DEPARTMENT}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.DEPARTMENT}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.DEPARTMENT}:${SCOPE.UPDATE}`,
    DELETE: `${RESOURCE.DEPARTMENT}:${SCOPE.DELETE}`,
  },
  EMPLOYEE: {
    VIEW: `${RESOURCE.EMPLOYEE}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.EMPLOYEE}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.EMPLOYEE}:${SCOPE.UPDATE}`,
  },
  CLIENT: {
    VIEW: `${RESOURCE.CLIENT}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.CLIENT}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.CLIENT}:${SCOPE.UPDATE}`,
  },
  CONTRACT: {
    VIEW: `${RESOURCE.CONTRACT}:${SCOPE.VIEW}`,
    CREATE: `${RESOURCE.CONTRACT}:${SCOPE.CREATE}`,
    UPDATE: `${RESOURCE.CONTRACT}:${SCOPE.UPDATE}`,
  }
}
